#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.3.22~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://sshwifty-demo.nirui.org/"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.22-beta-release-prebuild/sshwifty_0.3.22-beta-release_linux_amd64.tar.gz"
    amd64.sha256 = "b5a7155bd9cf3da6c299f21eb0ca8789fce7cb61b6a003804f97a911befcd9c1"
    arm64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.22-beta-release-prebuild/sshwifty_0.3.22-beta-release_linux_arm64.tar.gz"
    arm64.sha256 = "d193d75ab3664118c7fc0adcc25d6639d0b9fb86a22f2895bf17e1d1d0639f5c"
    armhf.url = "https://github.com/nirui/sshwifty/releases/download/0.3.22-beta-release-prebuild/sshwifty_0.3.22-beta-release_linux_arm.tar.gz"
    armhf.sha256 = "a5a764f03a60dd507576d6cec9396a283bb7f01be84dd37adaabc284de9507ae"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^(.*)-beta-release-prebuild$"
    autoupdate.asset.amd64 = "sshwifty_.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "sshwifty_.*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "sshwifty_.*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
