#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.4.9~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://sshwifty-demo.nirui.org/"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nirui/sshwifty/releases/download/0.4.9-beta-release-prebuild/sshwifty_0.4.9-beta-release_linux_amd64.tar.gz"
    amd64.sha256 = "18fd24ae319665063d74b1aa85dd55ff64dd33958aff47985c81fa8e6b16bf50"
    arm64.url = "https://github.com/nirui/sshwifty/releases/download/0.4.9-beta-release-prebuild/sshwifty_0.4.9-beta-release_linux_arm64.tar.gz"
    arm64.sha256 = "e8497c92bdc9f0bf73785532c8414f413f4b1979496ee8f2840c5784d0943926"
    armhf.url = "https://github.com/nirui/sshwifty/releases/download/0.4.9-beta-release-prebuild/sshwifty_0.4.9-beta-release_linux_arm.tar.gz"
    armhf.sha256 = "44e7e44cd84ed8df2b6ffbfa82b7cd0ac1c7f8c9afc0ce6be614f47f4223caaa"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^(.*)-beta-release-prebuild$"
    autoupdate.asset.amd64 = "sshwifty_.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "sshwifty_.*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "sshwifty_.*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
