#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.4.7~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://sshwifty-demo.nirui.org/"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nirui/sshwifty/releases/download/0.4.7-beta-release-prebuild/sshwifty_0.4.7-beta-release_linux_amd64.tar.gz"
    amd64.sha256 = "f0383533989dd0c5d99296a338fa7f1e99ffd882a6e800fb380d4016c5c8f2d9"
    arm64.url = "https://github.com/nirui/sshwifty/releases/download/0.4.7-beta-release-prebuild/sshwifty_0.4.7-beta-release_linux_arm64.tar.gz"
    arm64.sha256 = "2ef6ff8ab4d3b4273fde38cfd4778c0e76dd2d586c59f808e66612e78011a72d"
    armhf.url = "https://github.com/nirui/sshwifty/releases/download/0.4.7-beta-release-prebuild/sshwifty_0.4.7-beta-release_linux_arm.tar.gz"
    armhf.sha256 = "26a04016437ec8d988ab92dd3911b4263b8070f6d49f257cf273c9ecd15833fa"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^(.*)-beta-release-prebuild$"
    autoupdate.asset.amd64 = "sshwifty_.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "sshwifty_.*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "sshwifty_.*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
