#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.3.18~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://sshwifty-demo.nirui.org/"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.18-beta-release-prebuild/sshwifty_0.3.18-beta-release_linux_amd64.tar.gz"
    amd64.sha256 = "cfca61a9faa8b9df20f72da3e97d27043c87f63385d20cd1a7bd7dce50f404a8"
    arm64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.18-beta-release-prebuild/sshwifty_0.3.18-beta-release_linux_arm64.tar.gz"
    arm64.sha256 = "398d2b777188c48f636bc15fd58bb65253c597280041c42cbd3a14ea55a5f4f8"
    armhf.url = "https://github.com/nirui/sshwifty/releases/download/0.3.18-beta-release-prebuild/sshwifty_0.3.18-beta-release_linux_arm.tar.gz"
    armhf.sha256 = "32985e796e82607d2c22ceeee09003889fc213b86ff9f85ce66e318468cf36fe"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^(.*)-beta-release-prebuild$"
    autoupdate.asset.amd64 = "sshwifty_.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "sshwifty_.*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "sshwifty_.*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
