#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.4.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://sshwifty-demo.nirui.org/"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nirui/sshwifty/releases/download/0.4.2-beta-release-prebuild/sshwifty_0.4.2-beta-release_linux_amd64.tar.gz"
    amd64.sha256 = "4ce7cb95023cad4a6920ac12861353f54d14b5c4cea80ea81fa8ba8cf182caa2"
    arm64.url = "https://github.com/nirui/sshwifty/releases/download/0.4.2-beta-release-prebuild/sshwifty_0.4.2-beta-release_linux_arm64.tar.gz"
    arm64.sha256 = "66637987619867afcb9723a347a25638b4fd77941e960bb4b8dad8ecbd43d55b"
    armhf.url = "https://github.com/nirui/sshwifty/releases/download/0.4.2-beta-release-prebuild/sshwifty_0.4.2-beta-release_linux_arm.tar.gz"
    armhf.sha256 = "bebf46703524bafca460368d22c6280f47b0a04711d44180daba18c11458cf4e"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^(.*)-beta-release-prebuild$"
    autoupdate.asset.amd64 = "sshwifty_.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "sshwifty_.*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "sshwifty_.*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
