#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.3.23~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://sshwifty-demo.nirui.org/"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.23-beta-release-prebuild/sshwifty_0.3.23-beta-release_linux_amd64.tar.gz"
    amd64.sha256 = "a3cd4f57347ede636204ec6a8db3a155da21fb1344e84c8cf7c0f3bc98e9b248"
    arm64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.23-beta-release-prebuild/sshwifty_0.3.23-beta-release_linux_arm64.tar.gz"
    arm64.sha256 = "a05c97c3a45d70484bf77e90f899cfc5a464d4394b5094ea6e7f8bf3d581eddf"
    armhf.url = "https://github.com/nirui/sshwifty/releases/download/0.3.23-beta-release-prebuild/sshwifty_0.3.23-beta-release_linux_arm.tar.gz"
    armhf.sha256 = "0f54dc8eafc6bfac19aa445b6be7368fc23c10a78774a6446fbe19281e67c758"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^(.*)-beta-release-prebuild$"
    autoupdate.asset.amd64 = "sshwifty_.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "sshwifty_.*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "sshwifty_.*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
