#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.3.14~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "free"
website = "https://example.com"
demo = "https://sshwifty-demo.nirui.org/"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/nirui/sshwifty/releases/download/0.3.14-beta-release-prebuild/sshwifty_0.3.14-beta-release_linux_amd64.tar.gz"
    sha256 = "6209e75aa9edcee6d20a4739ae077a7c2e9dfcec95f39632d0e439fb1694fdec"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
