#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sshwifty"
name = "Sshwifty"
description.en = "Web SSH & Telnet (WebSSH & WebTelnet client)"
description.fr = "Web SSH et Telnet (client Web SSH et Web Telnet)"

version = "0.3.15~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
demo = "https://sshwifty-demo.nirui.org/"
code = "https://github.com/nirui/sshwifty"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.15-beta-release-prebuild/sshwifty_0.3.15-beta-release_linux_amd64.tar.gz"
    amd64.sha256 = "c37c250bfa7b8b81e525cd9796b129bc7b6ef5e3ac5191feb2c14d44509d8c7e"
    arm64.url = "https://github.com/nirui/sshwifty/releases/download/0.3.15-beta-release-prebuild/sshwifty_0.3.15-beta-release_linux_arm64.tar.gz"
    arm64.sha256 = "15409d9defc6fe05d02f46695c3929ddca7fcc4624ac5d8a6e1d035917df1ee7"
    armhf.url = "https://github.com/nirui/sshwifty/releases/download/0.3.15-beta-release-prebuild/sshwifty_0.3.15-beta-release_linux_arm.tar.gz"
    armhf.sha256 = "b110ca32173738a8b5e11c872e111edd4358ce8be093536c4da2828eefffb668"

    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^(.*)-beta-release-prebuild$"
    autoupdate.asset.amd64 = "sshwifty_.*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "sshwifty_.*_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "sshwifty_.*_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
